# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(408, 458)
        MainWindow.setStyleSheet("color: #524f4e;;\n"
"font: 16pt \"Bahnschrift Correct\";\n"
"background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SearchArea = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.SearchArea.setStyleSheet("QPlainTextEdit {\n"
"  display: block;\n"
"  width: 100%;\n"
"  padding: 0 10px;\n"
"  margin-bottom: 5px;\n"
"  background: #E9EFF6;\n"
"  line-height: 40px;\n"
"  border: 1px solid #323639;\n"
"  border-radius: 10px;\n"
"  font-family: \"Roboto\";\n"
"  font-size: 10pt;\n"
"  color: #524f4e;\n"
"}\n"
"QPlainTextEdit::hover{\n"
"    box-shadow: 3px 3px 3px black;\n"
"}")
        self.SearchArea.setObjectName("SearchArea")
        self.verticalLayout.addWidget(self.SearchArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Gthtdjl = QtWidgets.QPushButton(self.centralwidget)
        self.Gthtdjl.setStyleSheet("QPushButton {\n"
"  text-decoration: none;\n"
"  outline: none;\n"
"  display: inline-block;\n"
"  width: 140px;\n"
"  height: auto;\n"
"  line-height: 45px;\n"
"  border-radius: 10px;\n"
"  margin: 0px 0px;\n"
"  font: 11pt \"Roboto\";\n"
"  text-transform: uppercase;\n"
"  text-align: center;\n"
"  letter-spacing: 3px;\n"
"  font-weight: 600;\n"
"  color: #524f4e;\n"
"  background: white;\n"
"  box-shadow: 0 8px 15px rgba(0,0,0,.1);\n"
"  transition: .3s;\n"
"}\n"
"QPushButton::hover {\n"
"    background: #2EE59D;\n"
"  box-shadow: 0 15px 20px rgba(46,229,157,.4);\n"
"  color: white;\n"
"  transform: translateY(-7px);\n"
"}")
        self.Gthtdjl.setObjectName("Gthtdjl")
        self.horizontalLayout.addWidget(self.Gthtdjl)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.AnswerArea = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.AnswerArea.setStyleSheet("QPlainTextEdit {\n"
"  display: block;\n"
"  width: 100%;\n"
"  padding: 0 10px;\n"
"  margin-bottom: 5px;\n"
"  background: #E9EFF6;\n"
"  line-height: 40px;\n"
"  border: 1px solid #323639;\n"
"  border-radius: 10px;\n"
"  font-family: \"Roboto\";\n"
"  font-size: 10pt;\n"
"  color: #000000;\n"
"}\n"
"QPlainTextEdit::hover{\n"
"    box-shadow: 3px 3px 3px black;\n"
"}")
        self.AnswerArea.setReadOnly(True)
        self.AnswerArea.setObjectName("AnswerArea")
        self.verticalLayout.addWidget(self.AnswerArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Gthtdjl.setText(_translate("MainWindow", "Gthtdtcnb"))
